name: 'Update chart tag in module.yaml file'

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_NAMESPACE: fybrik 
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  update_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TAG_PSAT }}
    - name: 'next_version'
      id: next_version
      uses: zwaldowski/semver-release-action@v1
      with:
        dry_run: true
        bump: patch 
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "${{ steps.next_version.outputs.version }}"
    - run: TAG=${{ steps.bump-semver.outputs.new_version }}-SNAPSHOT && echo $TAG
