name: 'Update chart tag in module.yaml file'

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_NAMESPACE: fybrik 
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  update_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TAG_PSAT }}
    - name: 'next_version'
      id: next_version
      uses: zwaldowski/semver-release-action@v1
      with:
        dry_run: true
        bump: ${{ … }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Get next patched version'
      id: bump-semver
      uses: actions-ecosystem/action-bump-semver@v1
      with:
        current_version: ${{ steps.next_version.outputs.version }}
        level: patch
    - run: TAG=${{ steps.bump-semver.outputs.new_version }}-SNAPSHOT && echo $TAG
