name: 'Update chart tag in module.yaml file'

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_NAMESPACE: fybrik 
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  update_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TAG_PSAT }}
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0 # Optional fallback tag to use when no tag can be found
    - run: echo "${{ steps.previoustag.outputs.tag }}"
    - run: TAG=${{ steps.previoustag.outputs.tag }}-SNAPSHOT && echo $TAG
