name: 'Update chart tag in module.yaml file'

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_NAMESPACE: fybrik 
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  update_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TAG_PSAT }}
    - name: 'Get Previous tag'
      id: get-latest-tag
      uses: actions-ecosystem/action-get-latest-tag@v1
    - name: 'Get next patched version'
      id: bump-semver
      uses: actions-ecosystem/action-bump-semver@v1
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: patch
    - run: TAG=${{ steps.bump-semver.outputs.new_version }}-SNAPSHOT && echo $TAG
